version: '3.9'
services:
  node:
    build: ./node
    expose: [5000]
    volumes:
      - ./node:/usr/src/app
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"
    depends_on:
      - node